version: '3.8'
services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:0.12.14
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4571:4571"
      - "127.0.0.1:${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=sa-east-1
      - DATA_DIR=/tmp/localstack/data
      - DISABLE_CORS_CHECKS=1
  k6-sqs:
    container_name: k6-sqs
    build: .
    network_mode: host
    user: root
    command: run /tests/send-message.js --vus 1 --duration 30s
    volumes:
      - ./tests:/tests
      - ~/.aws/:/root/.aws/
    environment:
      - AWS_REGION=sa-east-1
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=bar
      - AWS_ENDPOINT=http://localhost:4566